[build]
publish = "public"
command = "git submodule update --init --recursive --depth=1 && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.78.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"